# these are cache variables, so they could be overwritten with -D,
set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME} CACHE STRING "LSMIO Project")
#
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
#
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "LSMIO - An I/O Library for HPC Applications"
    CACHE STRING "Package description"
)

set(CPACK_VERBATIM_VARIABLES YES)
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/pkg")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/tybulut/lsmio/")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libadios2-mpi-c++11, libadios2-mpi-core")

if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
  set(CPACK_DEBIAN_ARCHITECTURE "amd64")
else()
  set(CPACK_DEBIAN_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
endif()

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_PACKAGE_CONTACT "sbulut@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Serdar Bulut <sbulut@gmail.com>")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

# application_x.y.z_amd64.deb
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
# Default: ONE_PER_Component
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)
# Pack only specified component
set(CPACK_DEB_COMPONENT_INSTALL YES)

set(CPACK_DEBIAN_LSMIO_FILE_NAME "liblsmio_${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_ARCHITECTURE}.deb")
set(CPACK_DEBIAN_LSMIO__PACKAGE_DEPENDS "libadios2-mpi-c++11, libadios2-mpi-core")
set(CPACK_DEBIAN_LSMIO_DEV_FILE_NAME "liblsmio-dev_${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_ARCHITECTURE}.deb")
set(CPACK_DEBIAN_LSMIO__PACKAGE_DEPENDS "liblsmio, libadios2-mpi-c++11-dev, libadios2-mpi-core-dev")

include(CPack)
